# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: notebook
email: sean.parent@stlab.cc
description: Slides from notebook
baseurl: "/notebook" # the subpath of your site, e.g. /blog
url: "https://sean-parent.stlab.cc" # the base hostname & protocol for your site
twitter_username: SeanParent
github_username:  sean-parent

# Build settings
markdown: kramdown
highlighter: rouge

exclude: ["sean-parent.bbprojectd/", "exclude/", "bs-config.js"]
exclude-tags: []

# github
github: [metadata]

#wire this up
comments :
  provider : disqus
  disqus :
    short_name : seanparent
